### ISSUE TITLE
General: LocalLang update

### ISSUE THREAD

**Issue by opi99** [T3Voila/templavoilaplus#312]
* Till yet, there are no v8 translation files
* See: https://github.com/pluspol-interactive/templavoilaplus-languagefiles

**Comment by jpmschuler** [comment]
FWIW: it seems since the switch to crowdin extensions don't have any requirements and we could switch to the official translation server for v8
see https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Internationalization/TranslationServer/Crowdin/ExtensionIntegration.html#crowdin-extension-integration

**Comment by opi99** [comment]
Requested crowdin access in the cig-crowdin-localization slack channel

**Comment by opi99** [comment]
Localization is done via crowdin, you can request changes on https://crowdin.com/project/typo3-extension-templavoilaplu
