### ISSUE TITLE
Verify PHP 8 support

### ISSUE THREAD

**Issue by outdoorsman** [T3Voila/templavoilaplus#346]
I noticed that `master` at still only supports up to PHP 7.4 and you mentioned elsewhere `templavoilaplus` hasn't been tested against PHP 8 yet. I'm personally running PHP 7.4, but see that **[PHP 7.4 community support is ending November 28, 2022](https://azure.microsoft.com/en-us/updates/community-support-for-php-74-is-ending-on-28-november-2022/)** so it seems imperative that we support PHP 8 or it will be insecure almost by the time it's released as non-beta. I will give you feedback on errors here if I'm able to get TV+ working on one of my sites.

**Comment by jpmschuler** [comment]
Probably the major issue is that currently no tests were done, rather than it not working. 

However as the current master still supports older LTS, too, this change needs to be postponed to 8.1/9 because we need a stable v8 first.

**Comment by outdoorsman** [comment]
Sure that sounds fine.

If you're going to do that in version 9, I'm just praying it won't take another year. I've noticed that a lot of extensions are moving toward more frequent major version changes. If we do find any issues to make it compatible with PHP 8 it wouldn't hurt to silently sneak those fixes in without "officially" supporting it though right?

**Comment by opi99** [comment]
PHP 8.0 and 8.1 are activated, so closing this issue.
If there are problems then we should open one issue for every problem as normally done.

**Comment by outdoorsman** [comment]
@opi99 I didn't initially notice you had tests set up for PHP, but that makes me feel even better about this extension seeing there's testing on it too. So thankful for the PHP 8 support now, I wasn't expecting it so soon but it will definitely get used!!!!!!!!!

**Comment by opi99** [comment]
The tests were done by @jpmschuler and are (coding)style tests, no functional or integration tests. The development themself was done with PHP8 in mind, that why was marking as compatible so easy (but yes, it could be that there is a bug which wasn't seen).

**Comment by outdoorsman** [comment]
Thanks for that clarification @opi99 ;) Still, glad to see the test though. Rock on!

**Comment by outdoorsman** [comment]
Thanks for that clarification @opi99 ;) Still, glad to see the test though. Rock on!

**Comment by jpmschuler** [comment]
A general note: most problems in PHP8 compatibility are due to syntax changes, language features and libraries:
- Thus having a linter in place covers a whole lot of the syntax problems (and the linter tests are green)
- The o language features, especially with typing, are currently barely used due to the big compatibility starting by 8LTS, so they are circumvented anyways - in seldom cases there are PHP7 NOTICES turn into PHP8 WARNINGS and WARNINGS turned into ERRORS, but that will easily be found with the acceptance tests which will be introduced in the next weeks
- The only other thing is that PHP8 allows some composer dependencies to have more recent versions, but that is in most cases covered by TYPO3 core tests, as TVP doesn't use any 3rd party package directly.

So I agree... There might some time where bugs come up by chance, but probably we could easily have no problem at all.
